### ISSUE TITLE
AttributeError: /usr/lib/libcsound64.so: undefined symbol: csoundCompileTreeAsync

### ISSUE THREAD

**Issue by jcstucki** [fggp/ctcsound#10]
Getting this error when I try to import ctcsound. I am using the ctcsound file that was shipped with  

sudo aptitude install csound, 

and have installed libcsound64-dev for the libcsound64.so file. I am attempting to run csound code on a Rasberry Pi 3. 

Symlink does not work.

**Comment by fggp** [comment]
csoundCompileTreeAsync was added in Csound 6.10. If your libcsound64.so file is less than 6.10 then you should use the ctcsound.py file that was shipped with your version of Csound
