### ISSUE TITLE
Problem executing example #2 (02-performing.ipynb)

### ISSUE THREAD

**Issue by dodiku** [fggp/ctcsound#2]
Hi,

Thank you for building this package!

I'm trying to run a code that is almost identical to the code on ``02-performing.ipynb`` (I have the same issue with the original code):

```python
import ctcsound
cs = ctcsound.Csound()

csd = '''
<CsoundSynthesizer>

<CsOptions>
  -o dac -m0
</CsOptions>

<CsInstruments>
sr     = 48000
ksmps  = 100
nchnls = 2
0dbfs  = 1

instr 1
idur      =         p3
iamp      =         p4
icps      =         cpspch(p5)
irise     =         p6
idec      =         p7
ipan      =         p8
 
kenv      linen     iamp, irise, idur, idec
kenv      =         kenv*kenv
asig      poscil    kenv, icps
a1, a2    pan2      asig, ipan
          outs      a1, a2
          endin
</CsInstruments>

<CsScore>
f 0 14400    ; a 4 hours session should be enough

i 1 1 1 0.5 7.06 0.05 0.3 0.5
;e 1.5

</CsScore>
</CsoundSynthesizer>
'''


print csd
ret = cs.compileCsdText(csd)
if ret == ctcsound.CSOUND_SUCCESS:
	cs.start()
	cs.perform()
	cs.reset()

pt = ctcsound.CsoundPerformanceThread(cs.csound())
pt.play()

pt.scoreEvent(False, 'i', (1, 0, 2, 0.5, 8.06, 0.05, 0.3, 0.5))
pt.stop()
pt.join()

del cs
```

The problem is that I heard the 'hardcoded' note ``i 1 1 1 0.5 7.06 0.05 0.3 0.5``, but I think that I don't get to add another scoreEvent ``(False, 'i', (1, 0, 2, 0.5, 8.06, 0.05, 0.3, 0.5))``, and therefore, I don't hear it.

My setup is:
- Python 2.7.12
- Csound 6.08
- Mac OS X 10.12.1

**Comment by fggp** [comment]
I modified your example from the print statement to the end:

print(csd)
ret = cs.compileCsdText(csd)
if ret == ctcsound.CSOUND_SUCCESS:
    cs.start()

    pt = ctcsound.CsoundPerformanceThread(cs.csound())
    pt.play()

    pt.scoreEvent(False, 'i', (1, 0, 2, 0.5, 8.06, 0.05, 0.3, 0.5))

    cs.sleep(2000)

    pt.stop()
    pt.join()

del cs


It's a good exercise to try to understand by yourself these modifications.
Of course, if you need more information, don't hesitate to ask me.

Regards

Francois

2016-12-09 9:34 GMT+01:00 Dror Ayalon <notifications@github.com>:

**Comment by dodiku** [comment]
Thank you so much for your help!
The code makes a lot of sense.

Anywhere I can find the complete documantation?

**Comment by fggp** [comment]
- API doc in the 'LEARN' menu on http://csound.github.io/
- Examples in different programming languages on
https://github.com/csound/csoundAPI_examples
- The docstrings in ctcsound.py
- The cookbook on https://github.com/fggp/ctcsound
- The API chapter (12A) on http://write.flossmanuals.net/csound/preface/

2016-12-09 18:07 GMT+01:00 Dror Ayalon <notifications@github.com>:

**Comment by dodiku** [comment]
Thanks!!
I actually know these resources.
Most of them are dealing with 'csnd6'.
Is the API for 'ctcsound' identical to the API for 'csnd6'?

**Comment by fggp** [comment]
The API is written in C. csnd6.py is a wrapper file to the API for Python
2.7, and it is automatically generated by SWIG, using some helper classes
to wrap C pointers and structures. ctcsound.py is another wrapper file to
the API for Python 2.x and Python 3.x as well. ctcsound is hand written and
it uses the numpy module to wrap C pointers and structures. ctcsound adopts
recent naming conventions. For example, supposing you created an object
called cs, the csoundGetVersion() function of the C API would be wrapped by
the cs.GetVersion() method in csnd6, while it would be wrapped by the
cs.version() method in ctcsound.

For me, the best source of information is to compare the csound.h and the
csPerfThread.hpp files from the Csound sources, which are the headers file
for the C/C++ API, to the ctcsound.py file. All these files include
detailed comments.

François
