### ISSUE TITLE
Can't import ctcsound

### ISSUE THREAD

**Issue by unriginal** [fggp/ctcsound#3]
I have this code:

import ctcsound

c = ctcsound.Csound()        # Create an instance of the Csound object
c.Compile('test1.csd')    # Compile a pre-defined test1.csd file
c.Perform()               # This call runs Csound to completion
c.Stop()                  # At this point, Csound is already stopped, but this call is here
                          # as it is something that you would generally call in real-world 
                          # contexts 
--------------------

Using Python 3.5, whenever I run this code, or try to import ctcsound at all, I get this error message.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-b46b98f49e5f> in <module>()
----> 1 import ctcsound

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctcsound.py in <module>()
    214 libcsound.csoundGet0dBFS.restype = MYFLT
    215 libcsound.csoundGet0dBFS.argtypes = [c_void_p]
--> 216 libcsound.csoundGetA4.restype = MYFLT
    217 libcsound.csoundGetA4.argtypes = [c_void_p]
    218 libcsound.csoundGetCurrentTimeSamples.restype = c_int64

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py in __getattr__(self, name)
    358         if name.startswith('__') and name.endswith('__'):
    359             raise AttributeError(name)
--> 360         func = self.__getitem__(name)
    361         setattr(self, name, func)
    362         return func

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py in __getitem__(self, name_or_ordinal)
    363 
    364     def __getitem__(self, name_or_ordinal):
--> 365         func = self._FuncPtr((name_or_ordinal, self))
    366         if not isinstance(name_or_ordinal, int):
    367             func.__name__ = name_or_ordinal

AttributeError: dlsym(0x10608b0e0, csoundGetA4): symbol not found

---------
I've moved the ctcsound.py into my modules folder. Am I doing anything wrong?

**Comment by danmackinlay** [comment]
At a guess, from [comments like this](http://csound.1045644.n5.nabble.com/Csnd-Some-ugens-td5753926.html#a5753931) I suspect that csoundGetA4 is new. Certainly that symbol is not in the version I have, which is version 6.08 from November 2016; whereas the csoundGetA4 comment appeared in January 2017. Probably if you build csound from the master branch source, @unriginal, you will find this works.

However, I noticed that if I comment out the lines referring to `csoundGetA4` in `ctcsound`, it works fine.

**Comment by danmackinlay** [comment]
in fact, @fggp implemented the `csoundGetA4` quite recently, in d955313555227, so I think I got that right. in my branch 7edb2bb98d69037b4ae3dba0257929baef6d8a5e the troublesome lines are commented out as a temporary fix.

**Comment by fggp** [comment]
I keep this version of ctscound.py updated with the develop branch of Csound. So unless you compile your own release of Csound from the develop branch, you should better use the ctcsound.py file shipped with the release version of Csound you are using.
