### ISSUE TITLE
add a setup.py

### ISSUE THREAD

**Issue by gesellkammer** [fggp/ctcsound#5]
It would be convenient to have a setup.py to install ctcsound as a normal package. A minimal setup.py would consist of

```python
from setuptools import setup

classifiers = """
Topic :: Multimedia :: Sound/Audio
Programming Language :: Python :: 2
Programming Language :: Python :: 3
"""

setup(name='ctcsound',
      version='0.0.1',
      description='Python bindings to the Csound API using ctypes', 
      classifiers=filter(None, classifiers.split('\n')),
      author='Name Surname',
      py_modules=['ctcsound'],
)
```

**Comment by fggp** [comment]
This is not a priority for me because ctcsound.py has been distributed with csound since the 6.07 version. As stated in the Readme file, this github repo is used for developing purpose.
