### ISSUE TITLE
Where is ctcsound.py installed in csound directory?

### ISSUE THREAD

**Issue by hhaudio** [fggp/ctcsound#7]
Hi, I'm trying to use ctcsound on a raspberry pi, where I installed csound via apt-get. I have checked that my csound version is recent enough (6.08). When I try to run a basic ctcsound test I get the following error: 

Traceback (most recent call last): 
  File "ctctest.py", line 2, in <module>
    import ctcsound 
ImportError: No module named ctcsound 

I realize this is because the path to ctcsound is not in my module paths. I could fix this easily, but I don't know where ctcsound.py got installed. Can someone answer that for me? Looking around directories is a bit of a wild goose chase. This information might be worth including in the readme.

**Comment by fggp** [comment]
When I build Csound on linux, ctcsound.py goes in ~/.local/lib/python/site-packages. You should run a find command on your system:
cd /
find . -name 'ctcsound.py'

**Comment by hhaudio** [comment]
Okay. When I install on raspbian via apt-get that directory does not exist. I tried reinstalling, following the instructions here: https://github.com/csound/csound/blob/develop/BUILD.md#raspian

But I get this error: 

> pi@raspberrypi:~ $ sudo apt-get build-dep csound
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  builddeps:csound : Depends: portaudio19-dev but it is not going to be installed
>                     Depends: libstk0-dev but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by fggp** [comment]
This is a Csound issue and raspberry pi and as I don't know raspberry pi, so I can't help you. What I suggested was to run the following commands:
cd /
find . -name 'ctcsound.py'
to find eventually where apt-get did copy ctcsound.py
