### ISSUE TITLE
Distributing python application that use ctcsound

### ISSUE THREAD

**Issue by GERMANOCARELLA** [fggp/ctcsound#9]
Hi, I need to distribute a python application that uses ctcsound. I'm on windows 10 and I installed csound 6.11. What I need for distributing python application without installing csound?

**Comment by fggp** [comment]
ctcsound needs Csound and Numpy. Moreover, ctcsound is now part of Csound. So if your application uses ctcsound, all you need to do is to tell the users that they must install Csound (>= 6.07) and Numpy to access Csound through ctcsound.
